num_landmarks: 1
horizon: 20
env_width: 10
env_height: 10
tau: 1.0

motion:
  A:
    _1: 1
    _2: 1
  B:
    _1: 1
    _2: 1
  W:
    _1: 0.005
    _2: 0.005
  landmark_motion_scale: 0.0

init_info: 0.001

FoV:
  radius: 1
  psi: 1.0471975511965976
  kappa: 1.0
  V:
    _1: 0.01
    _2: 0.01

lr: 0.00005
max_epoch: 200
batch_size: 50
num_test_trials: 10